labzero/lunch

src/components/RestaurantAddForm/RestaurantAddForm.js
src/components/RestaurantAddForm/RestaurantAddFormContainer.js
src/core/messages/en.json

Change placeholder text from “search places” to “add places” (using react-intl) in RestaurantAddForm input field

Change placeholder from “search” to “add” places

---

src/components/NameFilterForm/NameFilterForm.js
src/components/TagFilterForm/TagFilterForm.js
src/components/TagFilterForm/TagFilterFormContainer.js

disable all animations while filtering

---

.env.sample
.sequelizerc
README.md
db/seeds/20180108175137-admin-user.js

Would love to talk through the multi-promise part of this code when you have a chance.  Feels like there might be a better way to do this.

Add an admin superuser seed.

---

db/migrations/20180115184107-AddSortDurationToTeams.js
src/api/main/teams.js
src/components/NameFilterForm/NameFilterForm.js
src/components/TagFilterForm/TagFilterForm.js
src/components/TeamForm/TeamForm.js
src/components/TeamForm/TeamForm.scss
src/models/Team.js
src/models/index.js
src/styles/globalCss.scss

I am going to refactor this to include a description of what "vote duration" does, and clean up the label alignment, but I wanted to get a pair of eyes on this to make sure the gist of the PR is valid before refactoring.

Add owner ability to modify vote duration for sorting

---

package.json
src/actions/tests/decisions.test.js
src/actions/tests/restaurants.test.js
src/actions/tests/tags.test.js
src/actions/tests/teams.test.js
src/actions/tests/users.test.js
src/routes/helpers/tests/renderIfHasName.test.js
src/routes/helpers/tests/renderIfLoggedOut.test.js
src/routes/team/tags/index.test.js
src/routes/team/team/index.test.js
yarn.lock

fix failing tests using rewire

remove rewire from tests

---

src/api/main/teams.js
src/api/tests/teams.test.js
src/components/Header/Header.scss
src/components/Menu/Menu.scss

Return 409 if team slug already exists

---

src/actions/decisions.js
src/actions/restaurants.js
src/actions/tags.js
src/actions/team.js
src/actions/teams.js
src/actions/tests/decisions.test.js
src/actions/tests/restaurants.test.js
src/actions/tests/tags.test.js
src/actions/tests/users.test.js
src/actions/user.js
src/actions/users.js
src/api/helpers/loggedIn.js
src/core/ApiClient.js
src/core/tests/ApiClient.test.js
src/routes/login/Login.scss

Redirect to login page when receiving an API 401

---

src/actions/tests/websockets.test.js
src/helpers/tests/TagAutosuggestHelper.test.js
src/helpers/tests/canChangeUser.test.js
src/reducerMaps/tests/restaurants.test.js
src/selectors/tests/index.test.js

Add more test coverage

---

test/integration/helpers.js
test/integration/landing.spec.js
test/integration/login.spec.js
test/integration/other.spec.js
test/integration/restaurant.spec.js
test/integration/team.spec.js
test/integration/teams.spec.js

Should make puppeteer fail before mocha, so we can get some promise rejections and error logging from failing integration tests.

Add 5000ms timeout to all waits

---

README.md

Fix React Starter Kit link

---

src/routes/team/home/Home.scss

Map height fix on desktop

---

package.json
src/components/Html.js
yarn.lock

Specify Maps API version so Google sends release version. Fixes #124 and fixes #146.

Specify Google Maps API version

---

.env.sample
README.md

Add documentation/.env.sample variable for google server apikey

---

src/reducerMaps/tags.js
src/routes/team/home/Home.js

Close websocket when leaving home page to avoid situations where multiple websockets are open. Fixes #145.

Websocket fix

---

src/routes/team/home/Home.js

Only send ws ping if socket is open

---

src/reducerMaps/restaurants.js

fix SORT_RESTAURANTS

---

src/routes/team/home/Home.js

Fix WebSocket ping

---

src/components/NameFilterForm/NameFilterForm.js
src/components/TagFilterForm/TagFilterForm.js

Enable list animations except when changing filter

---

src/models/index.js

fix backend sorting

---

src/actions/decisions.js
src/actions/tests/decisions.test.js
src/components/RestaurantDropdown/RestaurantDropdown.js
src/components/RestaurantDropdown/RestaurantDropdownContainer.js
src/selectors/decisions.js

Add “last visited” date to restaurant dropdown

---

.circleci/config.yml
package.json
test/integration-setup.js
yarn.lock

Attempt to increase CI build test pass rate (#175)

increase slo-mo delay to 30

---

src/reducerMaps/restaurants.js

Handle duplicate restaurant notifications on front end (post vote, add restaurant, add tag).
Closes #189.

Handle duplicate restaurant notifications

---

src/routes/team/home/Home.js

Set max websocket reconnect timeout to 5 seconds.

---

db/migrations/20180503213015-AddIndicesToAppropriateColumns.js
src/models/Decision.js
src/models/RestaurantTag.js
src/models/Role.js
src/models/Team.js
src/models/Vote.js

Add indices to appropriate database columns.

---

src/components/Html.js

Move GA tracking code to top of <head>

---

src/components/ErrorPage/ErrorPage.js
src/routes/helpers/render404.js
src/routes/helpers/rootAction.js
src/routes/login/index.js
src/routes/main/invitation/create/index.js
src/routes/main/invitation/new/index.js
src/routes/main/landing/index.js
src/routes/main/new-team/index.js
src/routes/main/password/create/index.js
src/routes/main/password/edit/index.js
src/routes/main/password/new/index.js
src/routes/main/teams/index.js
src/routes/main/users/create/index.js
src/routes/main/users/new/index.js
src/server.js
test/integration/other.spec.js

Update page titles and description

---

src/styles/globalCss.scss

Move Google Maps touch warning above map markers

---

.babelrc.js
.env.sample
README.md
package.json
public/site.webmanifest
src/components/Html.js
src/components/Link/Link.js
src/server.js
src/service-worker.js
tools/webpack.config.js
yarn.lock

Add service worker with Workbox to allow caching of static assets and index page
Expand on site.webmanifest

Add PWA features

---

src/components/RestaurantAddForm/RestaurantAddFormContainer.js

Fix scrolling issue when adding restaurant and restaurant already exists.
Closes #218

Fix scrolling issue when adding restaurant

---

src/service-worker.js

 Don’t cache index page with service worker

---

src/components/Html.js
src/routes/login/index.js
src/server.js

Change opengraph tag for the login page

---

package.json
src/components/NotificationList/NotificationList.scss
yarn.lock

Also upgrade bcrypt as 1.0 doesn't support Node 10

Give notifications z-index so they appear on top of page root

---

src/api/team/votes.js
src/models/Vote.js

Fix vote race condition by wrapping in a transaction

---

src/server.js

Redirect www to root

---

src/components/AddUserForm/AddUserForm.js
src/middlewares/invitation.js
src/routes/main/invitation/create/Create.js

Add spam messaging for new users

---

package.json
src/client.js
yarn.lock

Don’t replace when moving to a new subdomain

---

src/components/AddUserForm/AddUserForm.test.js
src/components/Layout/Layout.test.js
src/components/RestaurantAddTagForm/RestaurantAddTagForm.test.js
src/routes/team/home/Home.test.js
yarn.lock

Fix test warnings

---

package.json
src/passport.js

A somewhat urgent bugfix that ensures new users can log in via Google.

Access Google profile email differently

---

.dockerignore
.gitignore
Dockerfile.local
docker-compose.yml

Updated docker-compose.yml and added a Dockerfile.local to bring up a dockerized version of lunch with a postgres instance.

Update docker-compose for doing bringing up local development instance

---

db/migrations/20230508195724-ChangeUserEmailToCitext.js
db/migrations/20230508203447-ChangeInvitationEmailToCitext.js
src/api/main/user.js
src/models/Invitation.ts
src/models/User.ts

Make user and invitation emails case-insensitive

---

src/components/HeaderLogin/HeaderLogin.js

Increase size of login button
